### ISSUE TITLE
Help & Suggestion

### ISSUE THREAD

**Issue by angelflo** [OptimBro/OptimNGINX#1]
Hi,

first of all, thanks a lot for work and to share this project !

I have some questions because i'm not expert in unix : 
1/ I currently use angristan/nginx-autoinstall, do you have an easy step by step workaround to switch to your OptimNGINX (because I need to use ModSecurity not included in angristan)
2/ Is it possible to update your OptimNGINX with last nginx mainline & openSSL like this is the case in last revision of angristan  https://github.com/angristan/nginx-autoinstall/commit/c80aa8d1febd400a6c856e5e870947d5c16c94a3
3/ In your conf/nginx.conf you use .vhost, is it possible to include an option in the script to choose between .vhost and .conf (currently use .conf with angristan) ?

Thanks again for all your work

**Comment by OptimBro** [comment]
Hi, 
First, sorry for my fast reply 😢 

Thanks for the feedback, I moved the project to this repository: https://github.com/OptimBro/OptimStack

Also, I stopped working on it due to lack of time. I'm also not a experienced guy on this but now I'll be maintaining it, and learning it.

Thanks (This really motivated me)
